//! Note types — the fundamental unit of knowledge in Mneme.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// How a note was created — determines its default trust score.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum Provenance {
    /// Written by the user directly.
    #[default]
    Manual,
    /// Imported from another system (Obsidian, Notion, etc.).
    Import,
    /// Clipped from the web.
    WebClip,
    /// Generated by AI.
    Generated,
}

impl Provenance {
    /// Default trust score for this provenance (0.0–1.0).
    pub fn default_trust(self) -> f64 {
        match self {
            Provenance::Manual => 1.0,
            Provenance::Import => 0.8,
            Provenance::WebClip => 0.6,
            Provenance::Generated => 0.4,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Provenance::Manual => "manual",
            Provenance::Import => "import",
            Provenance::WebClip => "web_clip",
            Provenance::Generated => "generated",
        }
    }

    pub fn parse(s: &str) -> Self {
        match s {
            "import" => Provenance::Import,
            "web_clip" | "webclip" => Provenance::WebClip,
            "generated" | "auto" => Provenance::Generated,
            _ => Provenance::Manual,
        }
    }
}

/// A note in the knowledge base.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Note {
    pub id: Uuid,
    pub title: String,
    /// Relative path from the vault root (e.g. "projects/agnos.md").
    pub path: String,
    /// SHA-256 hash of the Markdown content (hex-encoded).
    pub content_hash: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub last_accessed: DateTime<Utc>,
    /// How this note was created.
    pub provenance: Provenance,
    /// User-override trust score (None = use provenance default).
    pub trust_override: Option<f64>,
}

impl Note {
    pub fn new(title: String, path: String, content_hash: String) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            title,
            path,
            content_hash,
            created_at: now,
            updated_at: now,
            last_accessed: now,
            provenance: Provenance::Manual,
            trust_override: None,
        }
    }

    /// Effective trust score: user override if set, otherwise provenance default.
    pub fn trust_score(&self) -> f64 {
        self.trust_override
            .unwrap_or_else(|| self.provenance.default_trust())
    }
}

/// Request to create a new note.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateNote {
    pub title: String,
    /// Optional explicit path; if absent, derived from title.
    pub path: Option<String>,
    pub content: String,
    pub tags: Vec<String>,
    /// How this note was created (default: manual).
    #[serde(default)]
    pub provenance: Option<Provenance>,
}

/// Request to update an existing note.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateNote {
    pub title: Option<String>,
    pub content: Option<String>,
    pub tags: Option<Vec<String>>,
}

/// A note with its full content loaded.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoteWithContent {
    #[serde(flatten)]
    pub note: Note,
    pub content: String,
    pub tags: Vec<String>,
    pub backlinks: Vec<BacklinkInfo>,
}

/// Minimal info about a backlink (what links to this note).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacklinkInfo {
    pub source_id: Uuid,
    pub source_title: String,
    pub link_text: String,
    pub context: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_note_has_matching_timestamps() {
        let note = Note::new("Test".into(), "test.md".into(), "abc123".into());
        assert_eq!(note.created_at, note.updated_at);
        assert_eq!(note.created_at, note.last_accessed);
        assert_eq!(note.title, "Test");
        assert_eq!(note.provenance, Provenance::Manual);
        assert_eq!(note.trust_score(), 1.0);
        assert!(note.trust_override.is_none());
    }

    #[test]
    fn provenance_trust_scores() {
        assert_eq!(Provenance::Manual.default_trust(), 1.0);
        assert_eq!(Provenance::Import.default_trust(), 0.8);
        assert_eq!(Provenance::WebClip.default_trust(), 0.6);
        assert_eq!(Provenance::Generated.default_trust(), 0.4);
    }

    #[test]
    fn trust_override() {
        let mut note = Note::new("Test".into(), "test.md".into(), "abc123".into());
        note.provenance = Provenance::Generated;
        assert_eq!(note.trust_score(), 0.4);
        note.trust_override = Some(0.9);
        assert_eq!(note.trust_score(), 0.9);
    }

    #[test]
    fn provenance_from_str() {
        assert_eq!(Provenance::parse("manual"), Provenance::Manual);
        assert_eq!(Provenance::parse("import"), Provenance::Import);
        assert_eq!(Provenance::parse("web_clip"), Provenance::WebClip);
        assert_eq!(Provenance::parse("generated"), Provenance::Generated);
        assert_eq!(Provenance::parse("unknown"), Provenance::Manual);
    }
}
